### ISSUE TITLE
08.实现一个三角形

### ISSUE THREAD

**Issue by bycgxss** [bycgxss/Front-End-Interview#26]
```css
/*三角形的实现原理是利用了元素边框连接处的等分原理。*/
div{
  width: 0;
  height: 0;
  border-width: 100px;
  border-style: solid;
  border-color: tomato transparent transparent transparent;
}
```
