### ISSUE TITLE
09.单行文本溢出省略

### ISSUE THREAD

**Issue by bycgxss** [bycgxss/Front-End-Interview#27]
```css
/*单行文本溢出*/
p {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```
