### ISSUE TITLE
10.两栏布局

### ISSUE THREAD

**Issue by bycgxss** [bycgxss/Front-End-Interview#28]
```css
/*（1）利用浮动，将左边元素宽度设置为200px，并且设置向左浮动。将右边元素的margin-left设置为200px，宽度设置为auto（默认为auto，撑满整个父元素）。*/
.outer {
  height: 100px;
}

.left {
  float: left;
  height: 100px;
  width: 200px;
  background: tomato;
}

.right {
  margin-left: 200px;
  width: auto;
  height: 100px;
  background: gold;
}


/*（2）第二种是利用flex布局，将左边元素的放大和缩小比例设置为0，基础大小设置为200px。将右边的元素的放大比例设置为1，缩小比例设置为1，基础大小设置为auto。*/
.outer {
  display: flex;

  height: 100px;
}

.left {
  flex-shrink: 0;
  flex-grow: 0;
  flex-basis: 200px;

  background: tomato;
}

.right {
  flex: auto;
  /*11auto*/

  background: gold;
}
```
